### PR TITLE
Including doc about global usage, finally

### LINKED ISSUE #111: Doc about how to install Kint globally on PHP
I've easily installed Kint on my linux machine by using a custom, global dir for composer (like `/opt`, that I think was meant for that) + the `auto_prepend` feature of PHP. I could send a PR with those instructions if you feel the package should support that :)

### PR DESCRIPTION
**Pull request by igorsantos07**
Closes #111

### CODE REVIEW

**Comment by raveren** [comment]
oh thanks, that's a neat trick to use on a development machine, I'll test it out as soon as I get my dev machine running at home and will merge it if it causes no unexpected issues!

Thanks again!

**Comment by igorsantos07** [comment]
How's this? :)

**Comment by igorsantos07** [comment]
hey mister. this was forgotten :tongue:

**Comment by raveren** [comment]
I'm really sorry for the lack of updates - and it's definitely not forgotten, it's a great addition and I will be including it, but I loathe the current project page - it's terrible and outdated, I'm in the process of creating a new one from scratch and will credit you in the appropriate section.

**Comment by igorsantos07** [comment]
Oh, ok. But while you don't update it to the new version, why not including
the global snippet? It won't make the current page more outdated or worse,
I think. Haha

**Comment by pmqa** [comment]
I'm also interested in seeing that snippet! :)

**Comment by igorsantos07** [comment]
Hey @raveren! It's better to include new stuff in the current page than procrastinate a revamp on it forever and never update anything on it!
This new content is really useful and it's forgotten in this PR for more than a year, man.
You just need to accept the PR. You can recreate the page whenever you have time, unrelated to this change.
Please, merge this.

**Comment by igorsantos07** [comment]
Any news on this, @raveren? You really think it's better to wait **forever** to update the page and only then add a small feature to it?

**Comment by jnvsor** [comment]
> It's better to include new stuff in the current page than procrastinate a revamp on it forever and never update anything on it!

Hmm. Yep this is an old one. @igorsantos07 Could you please update this text to include `systemctl` server restart instructions (For newer distros), provide a link to the [php documentation on `auto_prepend_file`](http://php.net/manual/en/ini.core.php#ini.auto-prepend-file), and shorten it up a bit?

**Edit:** Also please provide a warning not to forget about it and put something in production that explodes because `Kint` is undefined!

**Comment by igorsantos07** [comment]
Three years after I wrote that doc and the PR got closed without a fix, waiting for the OP to keep fixing the ticket with every project iteration. Seriously?
I could even think about rewriting that a third time, but after that I just gave up on the project. Good luck lol

**Comment by igorsantos07** [comment]
Here I am again looking for this feature and discovered it was never merged in because it got so forgotten I needed to re-iterate multiple times to actually be able to contribute to the project. This is really sad.

**Pull request closed without merging**
