### PR TITLE
renamed "gray" theme to "aljinovic-gray"

### PR DESCRIPTION
**Pull request by aljinovic**
As requested in https://github.com/raveren/kint/pull/89#issuecomment-27296569

### CODE REVIEW

**Comment by raveren** [comment]
I did some work to the spacing&borders of your theme (did my best to stay faithful to the original intentions), and - just to confirm, the name `aljinovic-gray` does not really have a ring to it - nor is it easy to type in the config. Are you sure you want to name it that way? It's not really that much gray even :)

I'm keeping the name `gray` for now, confirm the name you want and I'll rename it.

**Comment by aljinovic** [comment]
you can name it as you want, I don't have any problems with that. I'll check the spacing and borders and give you some feedback.

**Comment by aljinovic** [comment]
Did you commit the spacing and borders?

**Comment by raveren** [comment]
I'll push it in a minute, as for the name, I'm thinking among the lines `ante-light-gray` - I'm terribly uncreative :D

**Comment by aljinovic** [comment]
I don't really care about the name, your call.

**Comment by aljinovic** [comment]
I had a different idea about tabs, I wanted to use them without bottom border (to look like tabs in any other web app), and little indented left so it's understandable they're not in the same nesting level as the content that opens by clicking on them.

**Comment by aljinovic** [comment]
In original theme, tabs are indented left, but in my theme, the concept is a bit different...

Original tabs: http://transfercroatia.com/transport/web/kint/examples/overview.php

**Comment by raveren** [comment]
I don't like how the tabs are now _either_, I just made some sense of it all, there were other issues with the spacing and I had changed the base LESS file that resulted in some needed altering in your theme.

You can now change the display of tabs much more easily, while everything else looks more consistently.

However there is still an issue that the way tabs are displayed is embedded in the main `_kint.less` (attached to top). 

It should be refractored to make no assumptions of how the final view should look&feel, but I had no time for that, I'll create a _note to self_ to do it.

In a perfect world, one should be able to choose how the tabs look independedly from the color scheme. A build-your-own theme functionality if you will.

**Comment by aljinovic** [comment]
Ok, I agree, but it's not that big of a problem anyway. Thanks for merging it ;)

**Comment by raveren** [comment]
While on the subject, there is the variable `@spacing` which is a modifier, and I did not introduce it into your theme.

Also, there's currently no font-size modifier, which would most likely be a nice addition. 

Come to think about it, the modifier should be a function that would take a number and spit out the resulting size (for example for small numbers, the function can decide when to return 1px and when 2px.

Sorry for the random thought stream, it'll be useful for me in the future :)

**Comment by aljinovic** [comment]
hehe no problem, knock yourself out :D

**Comment by raveren** [comment]
Again, I fixed other issues to the theme, inadvertently changing the tab style, please, go ahead and fix them back to your liking!

**Comment by aljinovic** [comment]
OK, I'll see what I can do with it.

**Comment by aljinovic** [comment]
I tried a different approach to tabs: http://transfercroatia.com/transport/web/kint/examples/overview.php?theme=aante-light

edit: whoops wrong url ;)

**Comment by raveren** [comment]
I don't think it's accessible from outside..

---

**Comment by aljinovic** [comment]
try now :D

**Comment by raveren** [comment]
...and nope, still no access :) how many domains do you own :) each demo is
in a different one :D

---

**Comment by aljinovic** [comment]
it's the same as last time: http://transfercroatia.com/transport/web/kint/examples/overview.php?theme=aante-light

**Comment by raveren** [comment]
Holly shit, that's lovely! You managed to pull off something really unique, wow!

Just for the fun of it, I want to play with border styles now (the new `border image` support in css3) to make it even more futuristic. Here's what a quick change does:

``` css
.kint dt.kint-parent + dd {
    border-left: 3px double #D7D7D7;
}
```



Note the border, I really want to fill it with gray :) although it will most likely render the theme unreadable, I can't wait to play with it :))

**Comment by aljinovic** [comment]
I'll merge it now.

Good idea with the borders, try it and see if you can make something functional with it.

**Comment by raveren** [comment]
how about your colleagues dark theme?

**Comment by aljinovic** [comment]
He still has some changes to do, than he'll make a pull request.

**Pull request closed without merging**
