### PR TITLE
implemented "open in new window"

### PR DESCRIPTION
**Pull request by aljinovic**
#46
- implemented "open in new window"
- fixed the bug with `_stepIsInternal()` method which didn't detect call_user_func_array inside `Kint` class as internal when short functions were called
- fixed some compatibility issues with older PHP versions that don't support "static::" and "$var::" static calls

### CODE REVIEW

**Comment by raveren** [comment]
I'd be really thankful if you could explain a reproduceable case of 

> fixed the bug with _stepIsInternal() method which didn't detect call_user_func_array inside Kint class as internal when short functions were called

**Comment by aljinovic** [comment]
When you call dd($var) from some_method, output should be:
"Called from /mnt/cifs/kint_master/demo.php line 69 in (some_method())"
Before, it was:
"Called from /mnt/cifs/kint_master/demo.php line 69 in (call_user_func_array())"

Reason was this line in _stepIsInternal():

``` php
return in_array( strtolower( $step['function'] ), self::$aliases['functions'], true );
```

All d(), dd(), ... methods contain "call_user_func_array()", and that method gets called from inside the class, but doesn't belong to a class so it's not detected as internal.

I added the check:

``` php
$fromThisFile = isset( $step['file'] ) && $step['file'] == __FILE__;
```

this just checks if the call was made from inside the kint class file and flags it as internal.

**Comment by raveren** [comment]
Aw fuck, I've already fixed that previously in another way, but did not commit the changes strangely :/

**Comment by raveren** [comment]
ah, also, I couldn't make your auto fetching of title work with traces - and it had some other very minor issues, so I substituted it for current date time for now.

**Pull request merged**
