### PR TITLE
Added 1.0 Branch Alias To `1.0.0-wip` Branch

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Also, is there any news on when this will be released and merged into the master?

### CODE REVIEW

**Comment by raveren** [comment]
Hey, not familliar with composer, what impact does your change make?

Also, I'm feeling terrible as it is, I'm swamped with real life and am trying to put in as much free time as possible into Kint, but there's been just too little of it, I'm getting there, please be patient...

**Comment by GrahamCampbell** [comment]
Sure, I'm not trying to rush you. My change means we can use `1.x` or `1.0.x` or `~1.0`, or any other valid version constraint to require the 1.0 version provided minimum stability is set to dev, or we can just add `@dev` to the requirement so `1.x@dev` would work too rather than trying to require the branch. This means that when you do release 1.0, nobody need make any changes to their composer.json files because they were already requiring the 1.0 branch. You can see an example of this here: https://github.com/panique/php-login/pull/405/files.

**Comment by raveren** [comment]
Uh-huh, I understand some of these words :D

But seriously, composer seems like an excellent tool, I'll try it out on my next freelance project.

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
