### PR TITLE
Added caching to classmethods parser...

### PR DESCRIPTION
**Pull request by aljinovic**
- added caching to classmethods parser
- added inheritance definition
- added definition file position

Demo: http://www.opengluco.com/demo/kint/demo.php

### CODE REVIEW

**Comment by raveren** [comment]
Woah, you're productive, superb work, man, thank you!

Do you plan implementing online documentation as in php-ref?

**Comment by aljinovic** [comment]
I'll look into online documentation when I have some more free time, it's a bit more tricky than I expected.

**Comment by raveren** [comment]
Alright, I'll just create an issue and whoever first finds the time, will implement it :)

**Comment by raveren** [comment]
Ok, this relates to #39, so I'll get around to it eventually if you won't beat me to it :)

**Comment by aljinovic** [comment]
Ok, great.

**Pull request merged**
