### PR TITLE
changed tabs layout in aante-light theme

### PR DESCRIPTION
**Pull request by aljinovic**
Demo: http://transfercroatia.com/transport/web/kint/examples/overview.php?theme=aante-light

### CODE REVIEW

**Comment by raveren** [comment]
pushed some changes myself, did you know about `microtime()`-based profiling? 



I must make a pretty presentation of all Kint's features someday.

**Comment by aljinovic** [comment]
cool, that's a nice feature, you should add it to demo also, it's a nice feature to have, no need to worry about scope of first microtime ;)

**Comment by raveren** [comment]
Yeah, it takes care of it, only shows average duration on 3rd call for example. 

Since some parts of the application at my job deal with Big Data, I use this feature a lot - to locate bottlenecks when things get slow :)

**Comment by aljinovic** [comment]
same here, but I never thought of implementing it into kint, great idea!

**Comment by raveren** [comment]
Thanks, it's really easy to use too:

``` php
d(
    microtime(),
    the_method_you_are_profiling(),
    microtime()
);
```

**Pull request merged**
