### PR TITLE
Added a 0.9 branch alias

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Can we pretty please have a 0.9.1 tag too?

### CODE REVIEW

**Comment by raveren** [comment]
Hey there, not really familiar with composer, what real-world consequences will there be if I merge this?

**Comment by GrahamCampbell** [comment]
It means people can install the latest changes from the master branch by using the version constraint `0.9.*@dev`. You should never use `dev-master` as a version constraint in composer. It's a terrible practise.

**Comment by GrahamCampbell** [comment]
@raveren Could we have a `v0.9.1` tag please?

**Comment by raveren** [comment]
https://github.com/raveren/kint/releases/tag/v0.9.1

will this do?

**Comment by GrahamCampbell** [comment]
Yeh, brilliant. Thanks. :)

**Pull request merged**
