### PR TITLE
added kint overview example page

### PR DESCRIPTION
**Pull request by aljinovic**
- added kint overview example page
- replaced static:: with self:: - php 5.0 doesn't support it

currently available here (would be cool to have it on main page): http://transfercroatia.com/transport/web/kint/examples/overview.php

### CODE REVIEW

**Comment by aljinovic** [comment]
There's a little compatibility issue with older versions of PHP that don't support namespaces.

In new code, some instances are created with backslash, ex: `new \ReflectionObject`, parser.class.php, line 364.

My old server has old PHP and Kint stopped working. I don't know if you're planing on using namespaces in Kint and loose support for older PHP versions, but it could make a problem for some people stuck on some legacy code and servers that can't upgrade that easily.

Also, method http://php.net/manual/en/reflectionproperty.setaccessible.php was introduced in PHP version 5.3, so it will cause problems too.

Errors: http://www.opengluco.com/kint/examples/overview.php

**Comment by raveren** [comment]
Wow dude, you're great! Yeah I'm definitely keeping compatibility **as wide as possible**, I've really put a lot of effort into it.

The `static` keyword is an interesting issue, it might prevent kint from being extendable, but I'll sort it out in the future..

**Comment by aljinovic** [comment]
I've been busy ;)
Here's a new theme: http://transfercroatia.com/transport/web/kint/examples/overview.php?theme=gray

**Comment by raveren** [comment]
Wow, great job! I've stayed up late yesterday too ;) but I'm not ready to release my changes..

The theme is excellent, there are some spacing issues, which need a little polishing, but it looks really good. The black one lacks a _little_ contrast IMHO to be readable enough, but it's up to you and I'll accept the pull requests as you think they should be :)

Thanks again, I'll credit you wherever possible!

**Comment by aljinovic** [comment]
I didn't do the black one. I can fix the spacing, just provide a screenshot so I can see what you're talking about ;)

**Comment by raveren** [comment]
here you go:

http://i.imgur.com/MLlj9r7.png

**Comment by aljinovic** [comment]
Nice catch with that spacing, check if it's ok now, same link.

I have a question about small "open in new window" arrow, was it intended only for trace? What should click on it do in normal debug (open only small trace in new window or should it be removed from there)?

arror

**Comment by raveren** [comment]
Well the small arrow is always there because you will sometimes want to pop-out outputs that are not collapsed - and it also gives a different result: the callee line is left present. I agree that it looks more cluttered, I'll have to ask my designer friend to come up with something.

Good job on the spacing, but here are other miniscule details I've noticed:

http://i.imgur.com/S1mTnSH.png

No 1. is present in two places (I think) and the empty cell in tabular data has the default background.

**Comment by aljinovic** [comment]
I think I managed to fix the problem with positioning, same link.

**Comment by raveren** [comment]
Hm, the tabs still look wonky.

**Comment by aljinovic** [comment]
What do you mean exactly?

**Comment by raveren** [comment]
Sorry for my brevity, I'm at work now. 

I must have looked at an older version, it looks fine now, trace tabs are still off a little though: 

http://i.imgur.com/HhETRLO.png

**Comment by raveren** [comment]
I mean the leftmost border

**Comment by aljinovic** [comment]
OK, I think I fixed it now ;) Didn't understand the problem at first...

http://transfercroatia.com/transport/web/kint/examples/overview.php?theme=gray

If you agree, I'll make a pull request for it.

**Pull request merged**
