### PR TITLE
Make kint minitrace more readable

### PR DESCRIPTION
**Pull request by willzyx-dev**
use light-grey color (#ddd) makes the minitrace very difficult to read in almost all kint themes. 
The only theme in which use #ddd has sense is "solarized-dark"

kint-minitrace

### CODE REVIEW

**Comment by jnvsor** [comment]
I can pretty much tell you right now that this isn't going to happen.
1. The text is deliberately grey. if you remove that rule it goes back to being black. It's grey because...
2. ...the minitrace is supposed to be tertiary information. If you want a backtrace there's both a special syntax `d(1)` and method `Kint::trace()` which will both give you far more information.
3. If you want custom colors, you should make your own theme instead of trying to change the default one. (You don't even need the theme, you can throw a more specific selector into the html completely outside of Kint)

**Comment by willzyx-dev** [comment]
@jnvsor Thanks for the speedy reply
1. I can agree with you that as tertiary information minitrace need a different color.. but use #ddd make the minitrace unreadable.
2. I know that kint provides ::dump(1) and other shorthands for getting the backtrace but is not what I'm looking for. I would like to be able to read the minitrace that kint provides
3. The point here is that use light-grey color (#ddd) makes the minitrace very difficult to read and this is an accessibility issue.

**Comment by jnvsor** [comment]
> very difficult to read and this is an accessibility issue

Unless you're using the default theme on a black background. At which point making it darker would be an accessibility issue.

People don't always use the same theme. This is why themes exist in kint - you should use them. (Or just chuck a single css rule into your output: `.kint footer ol>li{color:red}`)

In actual use I almost never use the minitrace. Does this have something to do with devel's not correctly setting a Kint alias so the minitrace shows the wrong stack frame from #193 ?

**Comment by willzyx-dev** [comment]
> Unless you're using the default theme on a black background. At which point making it darker would be an accessibility issue.

of course :) but I think that sites that use black background are a minority compared with sites that use a white/light color background

> In actual use I almost never use the minitrace. Does this have something to do with devel's not correctly setting a Kint alias so the minitrace shows the wrong stack frame from #193 ?

No this PR is absolutely not related to #193. For that problem we have updated kint to the latest tagged version and we are working for use \Kint::$aliases + \Kint::$returnOutput as you suggested

**Comment by jnvsor** [comment]
That's not going to work - the latest tagged version was 9 months ago and you already had that version. Haven't had a new tag released in ages.

But back on topic - perhaps you should rework this PR to give the minitrace a background. That way you can guarantee that it actually does improve readability

**Comment by willzyx-dev** [comment]
yes, adding a background color to the minitrace container can be a viable solution. But how to choose a decent default background? use white by default doesn't seems the right approach.. probably you need a default per theme background. have you any suggestions?

minitrace-container

something like this?

**Comment by jnvsor** [comment]
I think default white is fine - perhaps at 90% background opacity so the underlying theme shows through a bit. Throw in rounded bottom corners and inline-block to make it not full width and you should be done:



**Edit:** Or that, that should work too

**Comment by willzyx-dev** [comment]
oh I like the default white-90%-opacity background!! probably make the minitrace container full width can give a little more symmetry the the output :)

**Comment by jnvsor** [comment]
It's full-width by default. I was thinking about large debug outputs when I did that, there's an awful lot of empty space to the right of the mini trace compared to the rest of the output, and it just feels less "wrong" in my gut when it's not full width

**Comment by willzyx-dev** [comment]
> It's full-width by default. I was thinking about large debug outputs when I did that, there's an awful lot of empty space to the right of the mini trace compared to the rest of the output, and it just feels less "wrong" in my gut when it's not full width

It make sense :+1:  used inline-block for minitrace container

**Comment by jnvsor** [comment]
You should use `background: rgba(...` instead of `opacity` as opacity makes the contents fade out too

Also, I'm not sure solarized-dark even needs specific changes now - how does the white minitrace look?

**Comment by willzyx-dev** [comment]
The css changes was done in base.less and affect all themes. In solarized-dark.less (solarized-dark is the only theme that change the body background) the css for the container is overridden and setted to none

**Comment by jnvsor** [comment]
Ah, didn't realise it changed the background. Still, the opacity and border-radius lines are moot - and when you've done that try squashing them all into one clean commit - easier to review

**Comment by willzyx-dev** [comment]
> Still, the opacity and border-radius lines are moot

why do you think that these lines are moot? Do we need to add fallback for browsers that don't support these properties?

**Comment by jnvsor** [comment]
You should squash your commits. You've got duplicate CSS in between them, it's confusing at best.

**Comment by jnvsor** [comment]
Perfect. :+1:

**Comment by aaronbauman** [comment]
+1 for this, thanks!

**Comment by raveren** [comment]
Hello, thanks for the hard work, the mini-trace is definitely underdeveloped, but was so useful in everyday work, I chose to include it as it was. It currently still has issues with keyboard navigation ("what?" yes, press `d` and you can expand/collapse nodes, but navigating the minitrace throws js errors :/)

Anyway, why the rounded border and the inline display again? The default theme is an axiom, it was designed by a professional, I dare not change it myself. Let's keep this PR for the trace color only and I'll merge it instantly.

**Comment by jnvsor** [comment]
That was when it was a transparent background. Full width opaque background with nothing in it doesn't look too good (See for yourself)

**Comment by willzyx-dev** [comment]
Reverted the minitrace container background and the inline display

**Comment by jnvsor** [comment]
@willzyx-dev He didn't say you should get rid of the background - that's a legibility loss IMO

**Comment by raveren** [comment]
I tried the changes & the themes look very readable now, @jnvsor is there a real issue I'm not aware now? 

Note, I do know aante-light wasn't compressed by mistake, I'll push a quite big batch of changes later this week that fixes many issues and this is one of them...

**Comment by jnvsor** [comment]
@raveren In the old version, if you used the original theme on a black background you could read the trace. Now the background is gone the text will be completely illegible on a black background (I think @willzyx-dev did a blind revert and forgot about the background)

**Comment by raveren** [comment]
hey, @willzyx-dev, how's it going, I hope we didn't discourage you with our nitpicking :) Thanks for the initiative, what's your take on the background thing? :)

**Pull request merged**
